{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argo-app-of-apps
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: {{ $.Values.targetRevision }}
    path: {{ .path }}
    {{- if .values }}
    helm:
      valuesObject:
        {{- toYaml .values | nindent 8 }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace | default "default" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
