apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heaven-chrome-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theratzul/Heaven-Chrome.git
    targetRevision: HEAD
    path: k8s/argo-app-of-apps/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
